### ISSUE TITLE
TODO: handle binary data in the mysql backend

### ISSUE THREAD

**Issue by nbdsp** [perl6/DBIish#10]
I cannot figure out how to add binary data to MySQL table with INSERT query. When I try to insert some data into a binary column: 
```
my $q = "\x79\x80"; 
$st = $db.prepare("INSERT INTO main (hash) VALUES('$q')"); 
$st.execute(); 
```
I always get in the DB table 3 bytes: 0x79, 0xc2, 0x80.

As per MySQL site : ["mysql_query() cannot be used for statements that contain binary data; you must use mysql_real_query() instead. "](https://dev.mysql.com/doc/refman/5.6/en/mysql-query.html). And DBDish seems to use mysql_query() for queries.

**Comment by moritz** [comment]
It's not yet implemented (and patches very welcome).

Though it won't work the way you tried; rather you'll have to pass the binary data as a bind parameter of type Blob,  along the lines of

    my $q = Blob.new(0x79, 0x80);
    $st = $db.prepare("INSERT INTO main (hash) VALUES(?)"); 
    $st.execute($q); 

Mixing strings and binary data is a very bad idea (and leads to lots of problems in perl 5), and should be avoided.

**Comment by nbdsp** [comment]
Thanks for the response. AFAIU one has to be waiting till the support of Buf will be added to NativeCall in Rakudo? On IRC the topic of exchanging binary data with MySQL was recently being discussed and it was decided that until the Buf is not supported in NativeCall, it's better to use DBI:from<Perl5>.

**Comment by jonathanstowe** [comment]
I think the medium term solution here would be filing an RT on NativeCall so that it comes to someone's attention to fix, unless you're in IRC at just the right moment these things go un-noticed.

I'm not sure I am familiar enough with the code to offer any other immediate help.

**Comment by FROGGS** [comment]
Passing a Blob or Buf to a nativecall routine (such as $st.execute) is supported by NativeCall.
Returning a Blob/Buf on the other hand isnt. A native routine should return a CArray and can then turn that into something else.

**Comment by nbdsp** [comment]
@FROGGS - how one can to convert CArray to something else (e.g. Buf)? I tried to look into NativeCall.pm to see how Str is created from CArray, but hasn't managed to figure out.

**Comment by niner** [comment]
Inline::Perl5 does it the hard way:

            my $string_ptr = CArray[CArray[int8]].new;
            $string_ptr[0] = CArray[int8];
            my $len = p5_sv_to_buf($!p5, $value, $string_ptr);
            my $buf = Buf.new;
            for 0..^$len {
                $buf[$_] = $string_ptr[0][$_];
            }
            return $buf;

**Comment by FROGGS** [comment]
Yes, you have to do it the hard way, the reason for that is that CArrays don't know their element count by nature.
But somthing like this should work too:
```perl6
my $buf = Buf.new( |$carray[^$carray_elems] );
```

**Comment by Skarsnik** [comment]
Since now we have typed value. I could probably have row/allrows return Buf (or blob?) in case of binary data.
In mysql we have all the field information now. The issue is probably forcing the Str returned to not be encoded

**Comment by salortiz** [comment]
See https://github.com/perl6/DBIish/blob/master/t/26-mysql-blob.t for an usage example.
