### ISSUE TITLE
Deprecations should be reported through "is DEPRECATED" trait

### ISSUE THREAD

**Issue by bbkr** [perl6/DBIish#102]
Line
https://github.com/perl6/DBIish/blob/master/lib/DBDish/mysql/Connection.pm6#L48
reports deprecation multiple time from multiple threads because "once" is not thread safe method.

https://docs.perl6.org/routine/is%20DEPRECATED should be used instead.

**Comment by jonathanstowe** [comment]
Taken the opportunity to find and alter a few others too.
