### ISSUE TITLE
POD still mentions ParrotVM

### ISSUE THREAD

**Issue by bbkr** [perl6/DBIish#109]
https://github.com/perl6/DBIish/blob/master/lib/DBDish/mysql.pm6#L41

Maybe this whole section should be rewritten?
AFAIK there is no DBIish replacement project in progress.

**Comment by bbkr** [comment]
And there are pir exclusions in .gitignore. I think they can safely be removed too, I doubt current DBIish will run on last Rakudo with Parrot support (early 2015).

**Comment by JJ** [comment]
It's probably safe to remove it, you're right.
