### ISSUE TITLE
Can't install it via panda install DBIish: Cannot invoke null object

### ISSUE THREAD

**Issue by wbiker** [perl6/DBIish#11]
Hi,

I get following error when I try to install DBIish:

Cannot invoke null object
    in sub strip-pod at lib/Panda/Builder.pm:15
    in sub builder-order at lib/Panda/Builder.pm:56
    in method build at lib/Panda/Builder.pm92
    in method install at lib/Panda.pm:127
    in method iresolve at lib/Panda.pm:214
    in sub MAIN at panda:20
    in block <unit> at panda:87

I guess I am missing a module, because installation works on my desktop but not on my fresh Fedora 22 installation.

What is missin?

THX

**Comment by moritz** [comment]
This looks like a panda bug, not a DBIish bug, since the whole backtrace is inside panda.

Please report it as an issue in tadzik/panda.

Cheers,
Moritz

**Comment by wbiker** [comment]
OK, thx Moritz
