### ISSUE TITLE
grammar for pg arrays seems incorrect

### ISSUE THREAD

**Issue by bradclawsie** [perl6/DBIish#111]
https://github.com/perl6/DBIish/blob/ea5a9504fe6943fe2f12e5031ae14a169b6a2c2b/lib/DBDish/Pg/StatementHandle.pm6#L115

this will not capture, for example, ipv4 addresses...I think `\S+` may be more appropriate?

**Comment by moritz** [comment]
Be careful, `\S+` also matches unbalanced quotes, for example.

A better regex would probably be

   rule string { '"' $<value>=( <-["]>* ) '"' | $<value>=( \w+ ) }

That still doesn't handle escaped quotes inside a quoted string, but better than what we have now.

**Comment by bradclawsie** [comment]
I was actually referring to 

`$<value>=( \w+ )` 

(the second half)

the actual PG array I failed to parse was printed by psql as {127.0.0.1}

**Comment by moritz** [comment]
Well the argument against `\S+` is the same there.

Is there a list of literal forms that postgres supports somewhere?

**Comment by bradclawsie** [comment]
I would think in the second case, you actually want `.*`

https://www.postgresql.org/docs/10/static/arrays.html has a bunch of info about array

it doesn't seem like quotes are part of the output format at all

**Comment by moritz** [comment]
No, `.*` is basically always wrong. If you parse a list of comma delimited strings, both `.*` and `\S+` also match the commas the delimit the strings.

**Comment by bradclawsie** [comment]
Right, I should have clarified, I meant the array items themselves. Those should not be filtered further.

**Comment by moritz** [comment]
But without knowing what can or can't be inside an array item, you don't know where one ends and the next delimiter begins.

**Comment by bradclawsie** [comment]
its really just a problem for `TEXT` arrays. seems solvable but maybe not by perl6 grammars (I am not a perl6 grammars expert)

```
test=> \d t1
                            Table "public.t1"
 Column |  Type   | Collation | Nullable |            Default             
--------+---------+-----------+----------+--------------------------------
 id     | integer |           | not null | nextval('t1_id_seq'::regclass)
 ts     | text[]  |           |          | 
Indexes:
    "t1_pkey" PRIMARY KEY, btree (id)
```

and 

```
test=> insert into t1 (ts) values (array['a,b','c']);
```

```
test=> select ts from t1 where id = 2;
    ts     
-----------
 {"a,b",c}
```

The value will be quoted if PG needs to quote it

Sure there is a regex solution, not sure about a solution in the scope of the current grammar

**Comment by moritz** [comment]
Seems like the second branch should just be `<-[,]>+` then?

**Comment by bradclawsie** [comment]
Seems right. Seems like there should be a test for this. I cannot prepare this work myself right now but I could get back to you...or you could just try that out. Let me know what is best for you and thanks.
