### ISSUE TITLE
Warnings in tests

### ISSUE THREAD

**Issue by zoffixznet** [perl6/DBIish#116]
Generated on 2018.01:

```
t/36-pg-blob.t ............ ok
Potential difficulties:
    No values supplied to enum (does @options need to be declared constant?)
    at /home/cpan/.zef/store/DBIish.git/73e37ebd7b0bdf2117ced3f9102fcd000ba3b45c/t/36-pg-enum.t:74
    ------> my enum YesNo (@options)⏏;
```

**Comment by jonathanstowe** [comment]
This is now in the ```t/36-pg-enum.t``` : 

```
Potential difficulties:
    No values supplied to enum (does @options need to be declared constant?)
    at /home/jonathan/devel/perl6/3rdparty-modules/DBIish/t/36-pg-enum.t:74
    ------> my enum YesNo (@options)⏏;
```

It doesn't affect the test.

This is a compile time worry but the values of ```@options``` are being set at run-time, so the suggestion won't work (need to change ```@options```,) and ```quietly``` won't work.  So as much as I hate to do it, it's going to have to be ```no worries```.
