### ISSUE TITLE
Add support for common SQL types

### ISSUE THREAD

**Issue by JJ** [perl6/DBIish#119]
Trying to insert a [date into a timestamp field will yield an error (via StackOverflow)](https://stackoverflow.com/questions/49522489/cannot-resolve-caller-sqlite3-bind-do-not-understand-this-error-in-my-perl-6-sc/49530712#49530712) indicating that only these types are going to be supported in statements. 
```
   (DBDish::SQLite::Native::STMT $stmt, Int $n, Blob:D $b)
    (DBDish::SQLite::Native::STMT $stmt, Int $n, Real:D $d)
    (DBDish::SQLite::Native::STMT $stmt, Int $n, Int:D $i)
    (DBDish::SQLite::Native::STMT $stmt, Int $n, Any:U)
    (DBDish::SQLite::Native::STMT $stmt, Int $n, Str:D $d)
```
Either there is no conversion from native dates to SQL dates, or there's simply no support for that. There are probably other data structures that could be supported too, but this is the one I've bumped into.

**Comment by Skarsnik** [comment]
I think because sqlite does not give you date type.

**Comment by abraxxa** [comment]
That's exactly what I just found out.
I've used Hamsters (the Linux time tracking app) Sqlite3 database which shows 'timestamp' type columns in sqlitebrowser and I have no idea where this datatype comes from.

**Comment by abraxxa** [comment]
Please see me branch for a first take of the feature.
It seems sqlitebrowser displays `timestamp` in columns where it detects timestamp values although the datatype is `TEXT`.

**Comment by Skarsnik** [comment]
The issue, it should be possible to insert date object (just transform then to string). But it's not possible to fetch them as date if sqlite just tell us it's text. Or you need for the use to tell dbiish to expect a date
