### ISSUE TITLE
Test fails with old versions of Perl 6

### ISSUE THREAD

**Issue by JJ** [perl6/DBIish#132]
As is shown in [the latest test](https://travis-ci.org/perl6/DBIish/jobs/437043888). Maybe bump up the minimum version?

**Comment by jonathanstowe** [comment]
Is there any particular reason it is being test with 2017.08 specifically?  Otherwise I'll just bump it to say 2018.06 or something.

**Comment by nxadm** [comment]
Bump to minimal supported version. Lots of distros have older versions in their repos.

**Comment by jonathanstowe** [comment]
Well the earliest I can find off hand is 2018.02.1-137-g65874b15 and that works fine, if someone is in a position to try 2017.09 to 2018.01 faster than I would be able to that would be cool ;-)

**Comment by nxadm** [comment]
I made packages for those releases if they can help you:
https://github.com/nxadm/rakudo-pkg/releases/tag/v2018.01.1
https://github.com/nxadm/rakudo-pkg/releases/tag/2017.09.1%2B2

**Comment by jonathanstowe** [comment]
Well as it happens I appear to have got  lucky with the first try with 2017.09 - I'll update the travis config and see how that plays (there may be something travis specific at play.)

**Comment by jonathanstowe** [comment]
That looks good:  https://travis-ci.org/perl6/DBIish/  does anything else need to happen for this to be closable?

**Comment by JJ** [comment]
I guess not. Thanks!
