### ISSUE TITLE
MySQL driver does not support JSON types

### ISSUE THREAD

**Issue by samgwise** [perl6/DBIish#145]
Executing a select statement containing a field of type JSON results in the error:
`No type map defined for mysql type #245 at column 4
  in block  at /home/awards/.perl6/sources/8108A2944C9DA905A0FA0678EEBD282C64563AB4 (DBDish::mysql::StatementHandle) line 40`

JSON type is documented here: [11.6 The JSON Data Type](https://dev.mysql.com/doc/refman/5.7/en/json.html)

A temporary solution if you encounter this issue is to select the field as a char:
`SELECT (json_field AS CHAR(65536)) FROM ...` where the argument to char is the number of bytes allocated to hold the contents of the field (As described here: [12.10 Cast Functions and Operators](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html).

**Comment by jonathanstowe** [comment]
If I can get mysql working on this laptop I'll have a look at it today.   Is there a way of determining whether the mysql engine one is using has the support for JSON columns (given that the versioning scheme seems to differ between the various implementations,)  or is it just try to create a table with a JSON column and if it succeeds then proceed to test with it?

**Comment by salortiz** [comment]
I've just working in some pieces missed.
Comments welcome.

**Comment by jonathanstowe** [comment]
Just as well, as my mysql installation doesn't seem to be working.

**Comment by samgwise** [comment]
Thanks @salortiz, after cloning and installing via zef the error is gone :)

Unfortunately I'm also hitting a VM Panic:
`MoarVM panic: Memory allocation failed; could not allocate 4294967295 bytes`

In my excitement to report the JSON type error I missed reporting the allocation error :/
I assumed that the type error and the allocation error were connected but appears I was wrong.

Would you like me to create a new issue for the allocation error and close this issue off?

**Comment by samgwise** [comment]
Ok, Will do. Thanks again for all your work :)
