### ISSUE TITLE
DBIish and Text::CSV do not work together.

### ISSUE THREAD

**Issue by wbiker** [perl6/DBIish#16]
Hmm, probably not a CSV problem alone. However, I would like to use CSV and DBIish together in a script, but every time I include both and run it the following error is thrown:

Merging GLOBAL symbols failed: duplicate definition of symbol HLL

This happens in the DBIish.connect method.
I will this also post on the CSV repo.

$ perl6
> use DBIish
> use Text::CSV
my $dbh = DBIish.connect("SQLite", :database<new-database.sqlite3>)

**Comment by niner** [comment]
You may be running an outdated version of rakudo and/or Text:.CSV. I seem to remember a bug like this fixed in the past few weeks.

**Comment by wbiker** [comment]
You're right. After upgrading rakudobrew and build moar new, the litte test script wors fine.
thx
