### ISSUE TITLE
Not sure why the tests are failing.  (Is it due to not having a MySQL server running?)

### ISSUE THREAD

**Issue by cschwenz** [perl6/DBIish#18]
If this test failure really is due to not having MySQL server running, then I think the relevant tests should be changed to conditionally skip if they cannot connect (as I have limited resources and have chosen PostgreSQL as my database, I neither need nor want MySQL taking up resources as well).

    $ panda install DBIish
    ==> Fetching DBIish
    ==> Building DBIish
    ==> Testing DBIish
    Use of uninitialized value %ENV of type Any in string context  in block <unit> at t/01-ConnectConfig-PG.t:26
    # Using PGDATABASE: 
    t/01-ConnectConfig-PG.t ... 
    All 15 subtests passed 
    t/05-mock.t ............... ok
    # Connect failed with error DBD::mysql connection failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    t/10-mysql.t .............. ok
    # Connect failed with error DBD::mysql connection failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    t/25-mysql-common.t ....... ok
    t/30-Pg.t ................. ok
    Use of uninitialized value %*opts of type Any in string context  in block <unit> at EVAL_0:45
    NOTICE:  table "nom" does not exist, skipping
    t/35-Pg-common.t .......... ok
    t/40-sqlite-common.t ...... ok
    t/41-sqlite-exec-error.t .. ok

    Test Summary Report
    -------------------
    t/01-ConnectConfig-PG.t (Wstat: 0 Tests: 15 Failed: 0)
      Parse errors: No plan found in TAP output
    Files=8, Tests=260, 218 wallclock secs ( 0.44 usr  0.06 sys + 207.10 cusr  3.63 csys = 211.23 CPU)
    Result: FAIL
    test stage failed for DBIish: Tests failed
      in method throw at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
      in method install at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
      in method resolve at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:219
      in sub MAIN at /home/cschwenz/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
      in block <unit> at /home/cschwenz/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:95

    Failure Summary
    ----------------
    DBIish(
      *test stage failed for DBIish: Tests failed)

The perl6 version is:

    $ perl6 --version
    This is perl6 version 2015.07.1-854-g8876f4d built on MoarVM version 2015.08-15-g4b427ed

**Comment by FROGGS** [comment]
No, it seems to fail because you *have* postgres running, but the table it is testing for does not exist.
So the test is bogus me thinks.
I think the tests that rely on a running service and a certain table scheme should be activated for authors only. Via an environment flag like `DBIISH_AUTHOR_TESTING` or so...

**Comment by timo** [comment]
Actually, it looks like the  file|t/01-ConnectConfig-PG.t |still uses
"done" instead of "done-testing" and so the plan is wrong.

**Comment by moritz** [comment]
Fixed with bbaa0fd, I hope; please try again!

**Comment by cschwenz** [comment]
$ panda install DBIish
    ==> Fetching DBIish
    ==> Building DBIish
    ==> Testing DBIish
    Use of uninitialized value %ENV of type Any in string context  in block <unit> at t/01-ConnectConfig-PG.t:26
    # Using PGDATABASE: 
    t/01-ConnectConfig-PG.t ... ok
    t/05-mock.t ............... ok
    # Connect failed with error DBD::mysql connection failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    t/10-mysql.t .............. ok
    # Connect failed with error DBD::mysql connection failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    t/25-mysql-common.t ....... ok
    t/30-Pg.t ................. ok
    Use of uninitialized value %*opts of type Any in string context  in block <unit> at EVAL_0:45
    NOTICE:  table "nom" does not exist, skipping
    t/35-Pg-common.t .......... ok
    t/40-sqlite-common.t ...... ok
    t/41-sqlite-exec-error.t .. ok
    All tests successful.
    Files=8, Tests=260, 206 wallclock secs ( 0.37 usr  0.03 sys + 195.50 cusr  3.34 csys = 199.24 CPU)
    Result: PASS
    ==> Installing DBIish
    Copying blib/lib/DBDish.pm6 to /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/DBDish.pm6
    Copying blib/lib/DBIish.pm6 to /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/DBIish.pm6
    Copying blib/lib/DBDish/Pg.pm6 to /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/DBDish/Pg.pm6
    Copying blib/lib/DBDish/TestMock.pm6 to /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/DBDish/TestMock.pm6
    Copying blib/lib/DBDish/SQLite.pm6 to /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/DBDish/SQLite.pm6
    Copying blib/lib/DBDish/mysql.pm6 to /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/DBDish/mysql.pm6
    ==> Successfully installed DBIish

\o/  It worked!  Thanks!
