### ISSUE TITLE
fetchrow_hashref give a hash of str (with Pg)

### ISSUE THREAD

**Issue by Skarsnik** [perl6/DBIish#21]
fetchrow_hashref give a hash of str (not Str) typed value, preventing for using .perl on it for example.
Even when trying to copy the given hash into another hash it still retain the str type. I suspect it because the := operator is used when fecthing the row from Postgres.
Should it give just Str?

**Comment by moritz** [comment]
Please add example code with which one can reproduce this issue. Thank!

**Comment by Skarsnik** [comment]
hm, I suppose do a select request on a pg table then
use DBIish;
.... some pg connection and prepare request stuff
$select_req.execute();
my $hashref = $select_req.fetchrow_hashref();
my %hash;
for $hashref.kv -> $key, $value {
      say $value.^name; # will print str
       %hash{$key} = $value;
       say %hash{$key}.^name; # will print str
     }
 say %hash.perl; # will crash - This representation (P6str) does not support attribute storage

**Comment by moritz** [comment]
Please provide acutal code that I can run by copying it into a file. Try to reduce it to a minimal example that selects a constant. If you can't reproduce the error that way, include your DDL and some  data with which the error can be reproduced.

**Comment by Skarsnik** [comment]
This should work with any pg database (just change the information to connect)

http://pastebin.com/cnvgu7SX
