### ISSUE TITLE
Add postgresql array

### ISSUE THREAD

**Issue by Skarsnik** [perl6/DBIish#29]
Could be cool to have pg_array support, meaning fetch* should return an array for the array field and execute be able to work on array value.

Basicly it probably converting array string pg give us, they look like that: {NonSpace, "With Space"} and can be nested {{value, value}, {value, value}}

**Comment by azawawi** [comment]
Could you provide a sample usage scenario (i.e actual code snippet)?

**Comment by moritz** [comment]
I think I've changed my opinion here, and now posit that it's not DBIish's job to parse such values.

The Postgres C client library returns them as strings, so DBIish should return them as string too. If you want something that maps them to a more advanced data types (arrays to arrays, hstore to hashes, jsonb to arrays/hashes/strings/numbers/...), that belongs into an ORM.

If you disagree, please explain why it's DBIish's job.

**Comment by Skarsnik** [comment]
Well first DBI in perl5 does it. Array is a supported type defined in the SQL99 RFC. it's probably not only supported in Pg http://savage.net.au/SQL/sql-99.bnf.html#array specification 
I did not find the documentation of the Pg library but there is maybe some call that handle array
At least if you don't want a full support in DBIsh, providing a serialize/deserialize method somewhere could still be useful :)

**Comment by moritz** [comment]
Oh, I didn't know it was part of the SQL standard. If there's a way in which Postgres indicates that it's returning an array, I'm fine with it being implemented in DBIish after all.

Still, (de)serialization in general belongs into layer about DBIish, because it requires more meta information about the data types being used/returned.

**Comment by azawawi** [comment]
Actually our mapping is not 100% correct as far as I can see, please take a look at [pg_type.h](http://doxygen.postgresql.org/include_2catalog_2pg__type_8h.html). Namely this:

```C
#define 	INT2ARRAYOID     1005
#define 	INT4ARRAYOID     1007
#define 	TEXTARRAYOID     1009
#define 	OIDARRAYOID      1028
#define 	FLOAT4ARRAYOID   1021
#define 	CSTRINGARRAYOID  1263
```
and PostgreSQL documentation on [Arrays](http://www.postgresql.org/docs/9.4/static/arrays.html)

I am going to work on this one for the rest of the evening :+1:

**Comment by azawawi** [comment]
Initial implementation added in my forked repository. Please review https://github.com/azawawi/DBIish/commit/87d311f0e55052f067bba45ff53c4f938277dee3

**Comment by Skarsnik** [comment]
Thanks for you work.
I merged you modification into the current DBIish. I will close this ticket when tests will be added, if someone feel like doing so x)

**Comment by salortiz** [comment]
@azawawi What is the status of the offered tests?

**Comment by salortiz** [comment]
Reworked a little the array engine and now pass the test provided by @Skarsnik

**Comment by azawawi** [comment]
@salortiz Thanks for the fix. I am very sorry but I was busy doing other projects and forgot about this issue :+1:
