### ISSUE TITLE
Implement fetch*_typedhash in other drivers

### ISSUE THREAD

**Issue by Skarsnik** [perl6/DBIish#31]
For now only Pg can do it.

It consist mostly of adding a column_p6types method that return the list of perl6 type names for the column and a true_false method to handle Boolean value

**Comment by azawawi** [comment]
Can you confirm what drivers can implement that functionality? I thought we agreed earlier to keep it in the PostgreSQL driver for now.

**Comment by Skarsnik** [comment]
https://dev.mysql.com/doc/refman/5.7/en/mysql-fetch-field-direct.html for mysql for example

**Comment by Skarsnik** [comment]
Look like sqllite offers function to fetch value in a proper type (for now sqllite request everything as text), maybe letting each drivers define fetch_typed stuff is the best way
