### ISSUE TITLE
Handle execute done after finish on STH and Error

### ISSUE THREAD

**Issue by Skarsnik** [perl6/DBIish#34]
I found an interesting bug. Calling execute after finish on the sth make SQLite crash.
It's not that bad to fix, but what is the proper behavior in this case.
Die or return Nil?

**Comment by jonathanstowe** [comment]
Die

**Comment by salortiz** [comment]
Indeed a bug, DBI states: "$sth->finish Indicate that no more data will be fetched from this statement handle before it is either executed again or destroyed."
