### ISSUE TITLE
timestamp in postgresql (also possibly other types and other databases)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/DBIish#41]
``.allrows`` does not handle **timestamp** type correctly. That is, you just get ``Any``.

Adding this to [lib/DBDish/Pg/Native.pm6](https://github.com/perl6/DBIish/blob/master/lib/DBDish/Pg/Native.pm6#L150) solves the problem:
```perl6
      1114  => 'Str',   # timestamp
```
But it feels like it is supposed to create a DateTime object instead of just Str. What is required to implement that and should it even be implemented?

**Comment by Skarsnik** [comment]
That a good question. It should be easy to return a timestamp. I try to stick to 'basic' type when introducing typed value in DBIish and avoid handling date/time stuff. 
I fear that it will be expected to handle then when executing query if we start handling more complex type.

I don't know timestamp format in Pg but a adding `1114 => 'DateTime`' and in Pg/sth.pm doing ``when DateTime' {$value = DateTime.new($fieldvalue)}` should be enought

**Comment by Skarsnik** [comment]
Alright timestamp should give you a Str (and everything not listed) now.

**Comment by salortiz** [comment]
I think DBIish should map all standard SQL types to sensible Perl6 types, the drivers, when possible, implement them.

**Comment by salortiz** [comment]
Now in PostgreSQL, but keep open till in mysql and Oracle.
