### ISSUE TITLE
Check how to free data

### ISSUE THREAD

**Issue by Skarsnik** [perl6/DBIish#44]
Each backend does his own thing.
Pg will free the data returned when finish is called, for example.

In some case we probably want to have the GC take over (copying data?)

There is also something I remarked, it's maybe a NC bug, SQLite give me explicity managed Str wich will probably lead to leak, see https://gist.github.com/Skarsnik/7f2fee97d56c5acc1587 (I reverse expected/got)

It not that simple as "Always copy" in case a text field is big, we probably don't want to copy a 50Mb+ field. So etheir document for each backend what will happend or provide a way for the user to free the data.

**Comment by Skarsnik** [comment]
If nobody disagree I will go this way :
All the short text (not TEXT field) will give a copy to the user. If the field is less than an arbitraty lenght I will return a copy too.

Everything will be free on .finish. I will add DESTROY on the statementhandl role to force a call to finish if it's not already done. Or maybe a new method, I am surprised we did not already run into some issue with fetchall since it call finish (I think it's in mysql) at the end of fetching everything.

**Comment by abraxxa** [comment]
The Oracle fetching goes like this:
- allocate buffer per column
- fill it per fetched row, reusing the memory

No idea how to release the explicitly-managed Str memory regions...

**Comment by Skarsnik** [comment]
I think using free is the solution, but not sure how to give it the underlaying ptr of the Str

**Comment by salortiz** [comment]
The SQLite  problem with explicitly managed strings is fixed now.

Certainly we must review each driver for their specific problems.
