### ISSUE TITLE
Bundle SQLite libs

### ISSUE THREAD

**Issue by zoffixznet** [perl6/DBIish#46]
It would be nice if DBIish bundled all the C libs required for SQLite backend; same as Perl 5's DBI [DBD::SQLite driver](https://metacpan.org/pod/DBD::SQLite) does. 

This way apps, Since SQLite does not need any servers or anything, using just SQLite backened would not need anything but installing this module using panda.

**Comment by Skarsnik** [comment]
Hm, I prefer if panda/something provide sqlite if it's not installed on a *unix plateform.

**Comment by zoffixznet** [comment]
What about Windows? Also, I don't see how panda can handle this. The only way is installing the system package which sounds very evil and I rather it didn't.

**Comment by jonathanstowe** [comment]
Yeah, after all SQLite is distributed as a single file, specifically in order to be bundled like that.

The alternative would be some Alien::SQLite which could either bundle or download the sqlite and build a private library if necessary (then things could depend on it.)

The first thing is the easiest though

**Comment by Skarsnik** [comment]
My assuption for windows is "Provide all the thing"

And for the how. It had be discused to add sections in the meta file to give information about external dependancy like that.

**Comment by zoffixznet** [comment]
> My assuption for windows is "Provide all the thing"

What does that mean?

> And for the how. It had be discused to add sections in the meta file to give information about external dependancy like that.

I believe `mst` has been trying to solve this issue for Perl 5, and it's not an easy problem to solve. If using the package manager, you're risking breaking something on my system that depends on the installed version of the package.

I guess my point is there needs not be an external dependency for the end user, if the lib is bundled. I, as the end user, (a) risking messing up my system (whether manually or whether panda does it automatically), (b) installing system packages available to all, (c) maintaining those packages are up-to-date. If I'm writing a Perl 6 DBIish app, all I need is DBIish installed in my `~/.perl6`

What are the arguments against bundling it with this distro?

**Comment by jonathanstowe** [comment]
https://www.sqlite.org/selfcontained.html contains rebuttals of most of the arguments for *not* bundling it.

**Comment by Skarsnik** [comment]
Well on Windows you are always better to provide everything you need that counting on found them.

The external dependancy thing is mostly informative (and will be useful for distrib or people that package your module).

For this specific issue, It just I am not fan of having x copy of the same lib. I will probably want panda/whatever asking me if he should build a copy for the module. Also if you can this way, you probably want to provide binary version of sqlite. Assuming a compilater is here/alowed to run is weird if you think of a p6 program ending on a server.

**Comment by Skarsnik** [comment]
I am not stopping people for doing the work to bundle SQLite. It's just my opinion on the matter :)

**Comment by zoffixznet** [comment]
There doesn't seem to be a consensus, so I'll close this; at least until we see what happens with the panda installing external prepreqs
