### ISSUE TITLE
Cannot locate native library 'libmysqlclient.so':

### ISSUE THREAD

**Issue by gaorongchao** [perl6/DBIish#47]
$ perl6 a.pl
Asked to remove 2 spaces, but the shortest indent is 0 spaces  in any trim_heredoc at gen/moar/m-Perl6-Actions.nqp line 407
NativeCall: Consider adding the api version of the library you want to use, sub foo is native(mysqlclient, v1)
Cannot locate native library 'libmysqlclient.so': libmysqlclient.so: cannot open shared object file: No such file or directory
  in method setup at /home/grc/.rakudobrew/moar-nom/install/share/perl6/sources/CACD5A7E20E331ECC972E25DE01416C706AEF2C4 line 230
  in method CALL-ME at /home/grc/.rakudobrew/moar-nom/install/share/perl6/sources/CACD5A7E20E331ECC972E25DE01416C706AEF2C4 line 241
  in method connect at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/sources/4C37BD08F0F30D1CBC49E3EA0A9EBFC77488FF78 line 19
  in method connect at /home/grc/.rakudobrew/moar-nom/install/share/perl6/site/sources/ED75476A0A2EAFE784D44945DC029BB56264DEF1 line 9
  in block <unit> at a.pl line 2

**Comment by Skarsnik** [comment]
You will need to install probably the devel package that come along the package for the libmysqlcient.
Sadly the mysqlclient lib does not follow a proper api/abi versioning for its library (14-18 are abi compatible), so we can't put the abi/api version.
Alternavly you can use the DBIISH_MYSQL_LIB environment variable to tell DBIish where to find the libfile.

**Comment by gaorongchao** [comment]
I'm very sorry，but I do not know how to do now。I can not find the libfile. And what's the devel package is ? Please give me detail information to solve this problem.

**Comment by zoffixznet** [comment]
What OS are you on? On debian, just type `aptitude search libmysql` and find the `-dev` version and `sudo apt-get install ***` that dev version

**Comment by gaorongchao** [comment]
Thanks for you reply! I solve this problem by 

 sudo apt-get install libmysqlclient-dev

**Comment by Skarsnik** [comment]
Should I close this? salortiz added a version in mysql (18) and fixed the ENV solution.
