### ISSUE TITLE
SQLite native library not found in windows 8.1

### ISSUE THREAD

**Issue by isleofmax** [perl6/DBIish#5]
When I install DBIish in windows 8.1 it gives me an error:
Connect failed with error Cannot locate native library 'libsqlite3.dll'.
I've downloaded sqlite3 and I've the directory in my PATH variable but there's not libsqlite3.dll,
there's sqlite3.dll. I must download something else from sqlite website or the name in the module
is wrong?

Thanks

**Comment by zoffixznet** [comment]
Confirming the issue. I think the `.dll` *is* the one from [sqlite download page](https://www.sqlite.org/download.html#win32). I tried rename it it to `libsqlite3.dll` from `sqlite3.dll`, in which case DBIish does find it, but the tests fail.

I tried copying contents of `t/99-common.pl6` to `t/40-sqlite-common.t` and running the tests. But the script just bails out at `my $sth = $dbh.prepare("DROP TABLE IF EXISTS nom");`. Putting a `say` after it does nothing, even though if we wrap it in `try{ CATCH{}}`.

That's as far as I've gotten with this. I'll leave it to someone more knowledgeable to fix :)

Here's the output of tests:

```
C:\temp>panda install DBIish
==> Fetching DBIish
==> Building DBIish
Compiling lib\DBDish.pm6 to mbc
Compiling lib\DBIish.pm6 to mbc
Compiling lib\DBDish\mysql.pm6 to mbc
Compiling lib\DBDish\Pg.pm6 to mbc
Compiling lib\DBDish\SQLite.pm6 to mbc
Compiling lib\DBDish\TestMock.pm6 to mbc
==> Testing DBIish
t/05-mock.t ............... ok
# Connect failed with error Cannot locate native library 'libmysqlclient.dll'
t/10-mysql.t .............. ok
# Connect failed with error Cannot locate native library 'libmysqlclient.dll'
t/25-mysql-common.t ....... ok
t/30-Pg.t ................. ok
# Connect failed with error Cannot locate native library 'libpq.dll'
t/35-Pg-common.t .......... ok
t/40-sqlite-common.t ......
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 39/42 subtests
t/41-sqlite-exec-error.t ..
Dubious, test returned 5 (wstat 1280, 0x500)
Failed 3/3 subtests
Test Summary Report
-------------------
t/40-sqlite-common.t    (Wstat: 1280 Tests: 3 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 42 tests but ran 3.
t/41-sqlite-exec-error.t (Wstat: 1280 Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
Files=7, Tests=185, 10 wallclock secs ( 0.02 usr +  0.08 sys =  0.10 CPU)
Result: FAIL
test stage failed for DBIish: Tests failed
  in method install at C:\rakudo/languages/perl6/lib/Panda.pm:125
  in method resolve at C:\rakudo/languages/perl6/lib/Panda.pm:195
  in sub MAIN at C:\rakudo\bin\panda:20
  in sub MAIN at C:\rakudo\bin\panda:18
  in block <unit> at C:\rakudo\bin\panda:77


Failure Summary
----------------
DBIish
        *test stage failed for DBIish: Tests failed

C:\temp>
```

**Comment by azawawi** [comment]
It is now working on windows. Please see the following [example](https://github.com/perl6/DBIish/blob/master/examples/sqlite.p6). You need to modify  ```%*ENV<DBIISH_SQLITE_LIB>``` to the location of your SQLite DLL. Please make sure that you download the proper SQLite DLL (i.e. 32 or 64-bit) from [here](https://www.sqlite.org/download.html#win32).

I am closing this one. Please reopen if the problem persists. Thanks for your patience :+1:

**Comment by isleofmax** [comment]
I'm using windows 8.1 64-bit and with the 64 bit version of sqlite3 the example works fine. When I use the 32-bit version I've this error:

perl6 -IC:\Users\massimo\Desktop\Sviluppo\DBIish-master\lib sqlite.p6
Cannot locate native library 'sqlite3.dll': error 0xc1
  in method CALL-ME at lib/NativeCall.pm:226
  in method connect at C:\Users\massimo\Desktop\Sviluppo\DBIish-master\lib\DBDish\SQLite.pm6:19
  in method connect at C:\Users\massimo\Desktop\Sviluppo\DBIish-master\lib\DBIish.pm6:9
  in block <unit> at sqlite.p6:12

**Comment by azawawi** [comment]
@isleofmax  I guess your rakudo Perl 6 is 64-bit and that NativeCall cannot load 32-bit DLLs. Why do you need the 32-bit version?

Run this command please
```
perl6 -V | find "64"
```

**Comment by azawawi** [comment]
Thanks for your feedback.
