### ISSUE TITLE
Merge oracle branch

### ISSUE THREAD

**Issue by jonathanstowe** [perl6/DBIish#52]
In order to get @abraxxa's work in #49 merged, I've got it passing for postgresql and sqlite but it appears that the mysql type mappings differ from those of the other two.

If someone could determine what they are supposed to be and make the fix them in the 'oracle' branch then the branch can be merged and all will be good.

**Comment by Skarsnik** [comment]
I will have a look at that tomorrow, if nobody do it before that.

2016-02-22 18:56 GMT+01:00 Jonathan Stowe <notifications@github.com>:

> In order to get @abraxxa <https://github.com/abraxxa>'s work in #49
> <https://github.com/perl6/DBIish/pull/49> merged, I've got it passing for
> postgresql and sqlite but it appears that the mysql type mappings differ
> from those of the other two.
>
> If someone could determine what they are supposed to be and make the fix
> them in the 'oracle' branch then the branch can be merged and all will be
> good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/DBIish/issues/52>.
>



-- 
Sylvain "Skarsnik" Colinet

Victory was near but the power of the ring couldn't be undone

**Comment by jonathanstowe** [comment]
Nice one :)

**Comment by salortiz** [comment]
I'm working on it.

**Comment by salortiz** [comment]
The branch It's ready.
Mysql have problems with the new tests, so I resurrect t/99-common.pl and t/25-mysql-common can switch between both test systems using an ENV var.
You can see the results in https://travis-ci.org/perl6/DBIish
I decided to wait for their comments prior to the merge.

**Comment by salortiz** [comment]
Found the problem. Was in the new tests!
