### ISSUE TITLE
Numeric types in DBIish

### ISSUE THREAD

**Issue by salortiz** [perl6/DBIish#55]
To facilitate the oracle branch merge, I let the "All float is Rat" change to survive, but only as an interim  solution.

The SQL standard defines NUMERIC and/or DECIMAL, as an exact, arbitrary (user decided) precision number *and* FLOAT, REAL, and DOUBLE as inexact, variable-precision numbers, usually mapped to native IEEE-754 implementations.

All DBDish drivers should support both kinds of numbers: `Rat` or `FatRat` (depending of desired precision) is the natural option to represent the first and `Num` the second.

We need to agree on a minimum set of data-types to test for in the common test suite, the current set `varchar`, `bigint` and `numeric(5, 2)` is insufficient.

**Comment by Skarsnik** [comment]
Not all drivers support different float numeric representation like SQLite.
But yes, it's probably a good idea.

**Comment by abraxxa** [comment]
My take on floats was to use the Perl 6 type which is the default when you write `my $float = 4.85;` which is Rat.
This has also the advantage of not having the usual float rounding errors.
Are there any downsides from your point of view which I've missed? Performance?

**Comment by salortiz** [comment]
@abraxxa if you write 'float' when you are thinking Rat  is your business :-)

The real problem is that DBIish should support and handle well the data in a Data Base not necessarily designed to be Perl 6 specific.
If a DBA uses, for wherever reason IEEE-754 types, the program needs to handle them in a predictably way, for example if a field in my DB contains the DOUBLE 1e+287 I want to see `1e+287` and that operations with it run at native speed.

As DB systems are richer in types, the best option is to design DBIsh with plugable types conversions, not fixed ones.

**Comment by salortiz** [comment]
From https://github.com/perl6/DBIish/commit/c57a200f4922a51b2dd3e133aa1f01af8a289516 all drivers after `prepare` expose in `$sth.column-types[$col]`, the *known* field types to be returned.
In the SQLite case, where the column type is dynamic (and NUMERIC don't exist), the user can set the desired type before row fetching.
See https://github.com/perl6/DBIish/blob/master/lib/DBIish/CommonTesting.pm6#L216 for an example.
This mechanism will be generalized and extended for other drivers.
So I'm closing this issue.

**Comment by abraxxa** [comment]
Salvador you rock! Thanks for pushing DBIish forward!
