### ISSUE TITLE
[SQLlite]  execute(... does not raise all errors (eg. unique constrain)

### ISSUE THREAD

**Issue by jantz** [perl6/DBIish#6]
If you try to insert a row with the same primary key you should get a unique constrain.
```perl6
use v6;
use DBIish;

my $dbh = DBIish.connect("SQLite", :database<example-db.sqlite3> :RaiseError);

my $rv = $dbh.do('DROP TABLE IF EXISTS foo');
my $sth = $dbh.do('CREATE TABLE foo (id int PRIMARY KEY NOT NULL)');

$sth = $dbh.prepare('INSERT INTO foo (id) VALUES ( ? )');
my $res = $sth.execute(1);
$res = $sth.execute(1);
$dbh.disconnect;
```
The SQLlite lib raise that but, SQLite.pm6 does not get it. The following naive patch fix that for me, but i'm sure i missed something. (I'm new to this git, github, perl6, perl tests thing, so i choose this way...)
```perl6
diff --git a/lib/DBDish/SQLite.pm6 b/lib/DBDish/SQLite.pm6
index 5bc70b0..86daf46 100644
--- a/lib/DBDish/SQLite.pm6
+++ b/lib/DBDish/SQLite.pm6
@@ -116,6 +116,9 @@ class DBDish::SQLite::StatementHandle does DBDish::StatementHandle {
             push @strings, $v;
         }
         $!row_status = sqlite3_step($!statement_handle);
+        if $!row_status != SQLITE_ROW and $!row_status != SQLITE_DONE {
+            self!handle-error($!row_status);
+        }
         self.rows;
     }
```
Of course a test needs to be added, but in the moment i don't know how to implement it.

**Comment by moritz** [comment]
Thanks, looking at it now. I've written a test already :-)

**Comment by moritz** [comment]
Thanks for the report and the patch. It earned you a commit bit, so in future you can push your patches directly. Welcome to Perl 6! Though if you prefer, I can still review them.
