### ISSUE TITLE
Is smarter C library version detection possible?

### ISSUE THREAD

**Issue by bbkr** [perl6/DBIish#60]
The issue is that OS X brew for example already switched to ```libmysqlclient.20.dylib``` while code still tries to load v18. As the result  tests are not executed during module installation. This can be solved by setting ```DBIISH_MYSQL_LIB``` but that method is:

* not user-friendly
* potential security issue, by modifying env variable to full path someone can load fake library from not trusted location without having write access to code

Is autodetection possible in latest NativeCall?

**Comment by Skarsnik** [comment]
It's not NativeCall job to do that, since it depend for each library. libmysqlclient is to blame to not following the libname.majorversion pattern that is desired (under os X and unix like). The env variable is the best solution.

**Comment by bbkr** [comment]
Thanks for explanation.

So maybe to address security issue it can be changed to ```DBIISH_MYSQL_LIB_VERSION=18``` and corresponding

```perl6
sub MyLibName {
    guess_library_name(('mysqlclient', Version.new(%*ENV<DBIISH_MYSQL_LIB_VERSION> // 18)));
}
```
?

Or checked that ```DBIISH_MYSQL_LIB``` does not contain full path?

**Comment by Skarsnik** [comment]
The goal of the %env variable is to be able to put a full path, like if your install the lib on your home directory. It's really not secure yes, but there is not a easy solution probably.

**Comment by salortiz** [comment]
@bbkr Can you try with latest?
Before v0.6.0, I'll re-add environment variable override, a more sane approach is now possible.

**Comment by bbkr** [comment]
I've tested latest version and it works. Awesome, thanks!
However test fails:

```
# Failed test 'Indeed libmysqlclient.20.dylib'
# at t/03-lib-util.t line 11
# expected: 'libmysqlclient.so.18'
#      got: 'libmysqlclient.20.dylib'
```

Maybe it should check if found library name matches pattern instead of comparing to hardcoded linux variant of library?

**Comment by salortiz** [comment]
@bbkr Yes, the test in fact was naive, only testing if detection works, but i think the issue is solved.
I'm now testing a better approach.

**Comment by salortiz** [comment]
@bbkr I think that the issue with the test is now fixed.
Can you confirm that?

**Comment by bbkr** [comment]
```
t/03-lib-util.t ........... ok
```

Thanks!
