### ISSUE TITLE
perl6 rakudo-star 2016-04 DBIish v0.5.6 - very slow retrieval of data records

### ISSUE THREAD

**Issue by bazzaar** [perl6/DBIish#63]
```
    perl6 rakudo-star 2016-04 DBIish v0.5.6 - very slow retrieval of data records
    Compared timings for simple retrieval of 6000 data records from Postgres DB using this code :
    
    my $sth = $dbh.do(q:to/STATEMENT/);
    set search_path TO music
    STATEMENT
    $sth = $dbh.prepare(q:to/STATEMENT/);
    SELECT artist, album, track, incorp
    FROM trackdata
    STATEMENT
    $sth.execute();
    my $arrayref = $sth.fetchall_arrayref();
    ( UPDATE based on johnathanstowe advice : ... or my @rows = $sth.allrows(); )
    
    ====================
    Installation 1A
    ====================
    rakudo-star-2016.01
    ====================
    bazzaar@linux:~> which perl6
    /home/bazzaar/rakudo/rakudo-star-2016.01/install/bin/perl6
    
    bazzaar@linux:~> panda info DBIish
    DBIish (version 0.5.6 available, "*" installed) <<< Note, installed DBIish (that came with R* 2016-01) didn't have a version number in the Meta.info file, just "*".
    Database connectivity for Perl 6
    Depends on: NativeHelpers::Blob
    State: installed
    
    bazzaar@linux:~/Documents> perl6 DBIish_pgsql_timing_test.p6
    -----------
    seconds
    -----------
    #start
    0.0005631
    0.3399387
    0.377477
    0.3879191
    Pow
    ....pulling records into $arrayref
    Wow
    2.4939554
    ... $arrayref.elems = 6220 records
    2.4966975
    2.5004059
    2.5035846
    #end
    
    ...
    ... ##### then installed latest DBIish into R* 2016-01 ####
    ...
    ====================
    Installation 1B
    ====================
    bazzaar@linux:~/Documents> which perl6                                                                                  
    /home/bazzaar/rakudo/rakudo-star-2016.01/install/bin/perl6
    
    bazzaar@linux:~/Documents> panda info DBIish
    DBIish (version 0.5.6 available, 0.5.6 installed)
    Database connectivity for Perl 6
    Depends on: NativeHelpers::Blob
    State: installed
    
    bazzaar@linux:~/Documents> perl6 DBIish_pgsql_timing_test.p6
    -----------
    seconds
    -----------
    #start
    0.0006852
    0.439804
    0.4622020
    0.517789
    Pow
    ....pulling records into $arrayref
    Wow
    193.6520393
    ... $arrayref.elems = 6220 records
    193.653642
    193.6546639
    193.660520
    #end
    
    ====================
    Installation 2
    ====================
    rakudo-star-2016.04
    ====================
    bazzaar@linux:~/Documents> which perl6
    /home/bazzaar/rakudo/rakudo-star-2016.04/install/bin/perl6
    
    bazzaar@linux:~/Documents> panda info DBIish
    DBIish (version 0.5.6 available, 0.5.6 installed)
    Database connectivity for Perl 6
    Depends on: NativeHelpers::Blob
    State: installed
    
    bazzaar@linux:~/Documents> perl6 DBIish_pgsql_timing_test.p6
    -----------
    seconds
    -----------
    #start
    0.000619
    0.3741873
    0.405408
    0.44036708
    Pow
    ....pulling records into $arrayref
    Wow
    146.9447798
    ... $arrayref.elems = 6220 records
    146.946464
    146.9473282
    146.95287678
    #end
```

**Comment by jonathanstowe** [comment]
I think the intent of 3849814c551e47e6158bf5bf4ed4ffb312434a25 is to encourage the use of .```.allrows``` rather than fetchall

**Comment by bazzaar** [comment]
Ahhh, then it could be I failed to move with the times .. dinosaur me :)

**Comment by salortiz** [comment]
@bazzaar  Can you test with latest? I found two separated issues that was affecting the performance.

**Comment by bazzaar** [comment]
```
salortiz++, thanks for such a prompt response :) 
I updated my DBIish to the latest (with panda --force install ) and reran the test :
bazzaar@linux:~/Documents> perl6 DBIish_pgsql_timing_test.p6
-----------
seconds
-----------
#start
0.000369
7.2215358
7.2411180
7.2805956
Pow
....pulling records into @rows with .allrows()
Wow
10.0325840
... @rows.elems = 6220 records
10.034001
10.0348920
10.03984815
#end

That's a big performance improvement on the data retrieval, very close to previous version performance - great news :)

The connection to the database is taking a bit longer though ( an extra 7 seconds, the db and server are running locally on this machine )

```

**Comment by salortiz** [comment]
@bazzaar  That delay can be the precompiling step of the new install, can you redo the test?

**Comment by bazzaar** [comment]
salortiz, you are one step ahead of me :) timings revised above.

**Comment by bazzaar** [comment]
Realise this isn't the right place to suggest additions to functionality of DBIish, been wondering about schema/table/constraint introspection, and data completeness, data utilisation of schema model, and auto sql generation ( ultimately ... in a Dancer-like web App ).

**Comment by salortiz** [comment]
@bazzaar Well :+1: 
Considering that `allrows` returns *types* values and is lazy, I think that the difference is fair.
OTOH, you can now avoid the copy and the implied memory assigning the result of `allrows` to an Scalar (and check the time involved)

```perl6
my $r = $sth.allrows;
for @$r -> @row {
   #use the row on demand
}
```

**Comment by salortiz** [comment]
Meanwhile can I consider this issue closed?

**Comment by bazzaar** [comment]
Thanks for the tip, yes please close the issue, thanks for the rapid response, and I'd be happy to run further timing tests on my db if it would be a help in the future.

**Comment by salortiz** [comment]
Thank you for your detailed report, and don't hesitate to report further issues.

**Comment by jonathanstowe** [comment]
@bazzaar I would tend to think that the sort of extended functionality you describe is the proper responsibility of another module which provides that degree of functionality.  People's opinions will differ about the way that something like that should be so it gives them the freedom to implement something that suits them.  The degree of abstraction in DBIish is about right now IMO.

Also having the kind of higher level interface in a separate module will also mean that DBIish doesn't get bent out of shape trying to support it and making it less useful for people who have other requirements.

**Comment by bazzaar** [comment]
```
@jonathanstowe I agree with what you say, that type of functionality does need to be in a module(s) dedicated to that task. If someone were to decide to create such a module for postgres I'd volunteer to help in some way.
```

**Comment by bazzaar** [comment]
@jonathanstowe I did some more thinking on this subject, and have written a perl6 grammar to parse a schema-only Pg_dump (ascii txt) file. My reasoning is that the pg_dump utility would do a much better job of extracting the database metadata, than any module I could write to do the same task. I'd be happy for this grammar to be tested against other Pg db schemas, if there was an interest to improve it. I'd be happy to do the additional coding/debugging in response to feedback. Currently the grammar runs to completion using Grammar::Debugger, though I have to add a few more action class methods to visualise all the match items.

**Comment by jonathanstowe** [comment]
I'm pretty certain that pg_dump does something along the lines of:

```
select * from information_schema.tables t join information_schema.columns c on c.table_name = t.table_name
```

Anyhow this is all completely unrelated to the original ticket.
