### ISSUE TITLE
Using DBIish on MacOS

### ISSUE THREAD

**Issue by ragnayev** [perl6/DBIish#96]
Hi,

Installed:

- rakudo-star-2017.07

in different directories
- MySQL community server
- Connector/C (libmysqlclient)

My pl6 script says:
**DBIish: DBDish::mysql needs 'mysqlclient', not found**

I exported to PATH mysql-server/bin and mysql-server/lib  - ERROR
then mysql-connector/bin and mysql-connector/lib - ERROR

how to make it working?

Thanks in advance

**Comment by jonathanstowe** [comment]
If the mysql client library is installed outside the standard library path then you will need to set the environment variable  ```DYLD_LIBRARY_PATH``` to include the directory where the library file is located.  For more on this see the ```dyld``` manpage.

**Comment by ragnayev** [comment]
Thank you very much. It's working now.
